# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: gds
services:
  neo4j:
    extends:
      file: ./neo4j.yml
      service: neo4j
