package com.uscis.dbis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExampleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExampleAllPropertiesEquals(Example expected, Example actual) {
        assertExampleAutoGeneratedPropertiesEquals(expected, actual);
        assertExampleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExampleAllUpdatablePropertiesEquals(Example expected, Example actual) {
        assertExampleUpdatableFieldsEquals(expected, actual);
        assertExampleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExampleAutoGeneratedPropertiesEquals(Example expected, Example actual) {
        assertThat(expected)
            .as("Verify Example auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExampleUpdatableFieldsEquals(Example expected, Example actual) {
        assertThat(expected)
            .as("Verify Example relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExampleUpdatableRelationshipsEquals(Example expected, Example actual) {
        // empty method
    }
}
